[package]
workspace = "../.."
name = "pangu-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pangu-model.workspace = true
pangu-dsl.workspace = true
pangu-ir.workspace = true
pangu-compiler.workspace = true
pangu-runtime.workspace = true
pangu-scheduler.workspace = true
serde_json.workspace = true

[[bin]]
name = "pangu"
path = "src/main.rs"

[target.'cfg(unix)'.dependencies]
libloading = "0.8.9"
