[package]
workspace = "../.."
name = "pangu-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pangu-model.workspace = true
pangu-compiler.workspace = true
libloading = "0.8.9"
serde.workspace = true
serde_json.workspace = true
