[package]
workspace = "../.."
name = "inferfabric-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
inferfabric-model.workspace = true
inferfabric-ir.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
inferfabric-dsl.workspace = true

[dependencies.serde]
workspace = true
